### ISSUE TITLE
ValueError: Image must be 2 dimensional to save as svg

### ISSUE THREAD

**Issue by netta-hub** [DeepLabCut/napari-deeplabcut#29]
hi :)

after tagging manually the frames through Napari, when I'm trying to save all the layers it shows an error:
ValueError: Image must be 2 dimensional to save as svg

thanks in advance for the help!

![Screenshot 2022-07-10 160133](https://user-images.githubusercontent.com/107629837/178145964-f2fc5b0f-ac0c-4d7d-8a3e-e2bf2fba3e7b.png)

**Comment by jeylau** [comment]
Hi @netta-hub! Do not save all layers, but only the Points layer.

**Comment by netta-hub** [comment]
thanks!
but now when I try to save it writes this (in the picture)
![image](https://user-images.githubu
![Picture1](https://user-images.githubusercontent.com/107629837/178232875-204b6325-cf63-4118-a884-99dbe0b293f3.png)
sercontent.com/107629837/178232189-360e29c2-6ca6-47d2-84e9-ad8347edf41a.png)

**Comment by jeylau** [comment]
You should only have 2 layers: the images + a Points layer that is automatically created either when dropping a h5 file or a config.yaml onto the canvas. It looks like you've manually added a Points layer yourself and added keypoints to it, which won't work well as this extra layer is not connected to the dropdown menus. Perhaps our Usage section may help you https://github.com/DeepLabCut/napari-deeplabcut#usage, let me know otherwise 😃
