### ISSUE TITLE
machine labels do not match up with napari images.

### ISSUE THREAD

**Issue by GxHam** [DeepLabCut/napari-deeplabcut#31]
Hi,

I also noticed that when loading machinelabels.csv with napari, the labels do not line up with the images, as the extracted points from DLC are not in image order, but the images loaded are. Here is an illustration (below). Notice that the order of frames is not sorted in the csv, resulting in misalignment when loaded into napari.

![image](https://user-images.githubusercontent.com/53009065/178645916-b719f888-2fe5-4d87-a479-dffc96fa8d0e.png)

**Comment by jeylau** [comment]
Hello @GxHam, you should only be loading the h5 files. Those are the ones used by deeplacut, whereas the CSV are just here to improve human readability.

**Comment by GxHam** [comment]
Hi @jeylau,

It was a typo. I have been loading the machinelabels-inter0.h5. But because the order in the h5 is not sorted as illustrated in the csv, the labels do not line up with the images in napari.

**Comment by GxHam** [comment]
Also, there is a bug where labels do not appear unless you load the entire folder first, then open the DLC plugin, and then reload the .h5 file. There seems to be an initialization problem with the dlc-napari plugin. If you load the folder after opening the DLC plugin, it refuses to read .h5 files and you have to restart napari.

**Comment by rs3966** [comment]
Hi - I am having the same exact issue - when loading machineiters_iterx.h5 with napari, the labels do not line up with the images always. I have the same issue when I re-extract more frames to label. Please advise.

**Comment by chris-rapson-formus** [comment]
Did anybody figure out how to resolve this? I'm seeing that the image filenames in the csv are listed in alphabetical order. A lot of my images have numerical filenames, and are loaded into napari in numerical order. i.e. '1,10, 100, 2' vs '1, 2, 10, 100'.

Is there a setting to choose how napari sorts the images?

I found #63 which links to a commit that loads images with `natsorted` instead of `sorted`. I wondered if that could that be my problem, but changing it back to `sorted` didn't help.

**Comment by chris-rapson-formus** [comment]
Did anybody figure out how to resolve this? I'm seeing that the image filenames in the csv are listed in alphabetical order. A lot of my images have numerical filenames, and are loaded into napari in numerical order. i.e. '1,10, 100, 2' vs '1, 2, 10, 100'.

Is there a setting to choose how napari sorts the images?

I found #63 which links to a commit that loads images with `natsorted` instead of `sorted`. I wondered if that could that be my problem, but changing it back to `sorted` didn't help.

**Comment by chris-rapson-formus** [comment]
I can confirm that the change pointed out in #63 (https://github.com/DeepLabCut/napari-deeplabcut/commit/23bbb6fe80c01c9a66a168f6db8e37a85865ae0b) doesn't help. The sort that happens in the `read_images` function is overridden by the `imread` function from `dask_images`. That uses `tifffile.natural_sorted` to sort the filenames again. the quick fix for me is to modify the source of `dask_image/imread/__init__.py` and change `natural_sorted` to `sorted`.

Changing code in somebody else's library is hacky as hell, so it would be better if the h5 load function would sort the labels in the same way as the images - perhaps with an option to use natural or alphabetical sorting. I tried modifying the `read_hdf` function to sort the DataFrame by the image paths, but I couldn't get it to work.

**Comment by MMathisLab** [comment]
@n-poulsen can you take a look at this? 

Or maybe @jeylau wants to advise ☺️
