### ISSUE TITLE
Multianimal Labelling: Moving to next animal after skipping a bodypart sets GUI back to first bodypart but not in actual labelling

### ISSUE THREAD

**Issue by hihosilvers** [DeepLabCut/napari-deeplabcut#41]
So I have a body parts list:
- tip
- middle

I have a list of individuals for multi animal labelling l1, l2, l3, etc ..

I'm on individual l33. I've labelled tip, the 'Keypoint selection' menu looks like this:
![image](https://user-images.githubusercontent.com/8742739/195895326-fd381386-b536-4dc5-837f-1f452137b1fd.png)

As I can't see the middle of l33, I will move onto l34 in the menu, and the GUI responds by resetting the body parts to tip:
![image](https://user-images.githubusercontent.com/8742739/195895540-51322744-bab5-4ed5-89f7-e73857ca8dea.png)

But when I go to label, it will label the point for the middle of l34, the tip of l34 is skipped and the next point to label is l35 tip.

**Comment by jeylau** [comment]
Hi @teejK, I suspect that this issue has just been fixed with [51d1b56](https://github.com/DeepLabCut/napari-deeplabcut/commit/51d1b5645b854a1ed9a7682f69992b9746be06d6); could you try `pip install -U git+https://github.com/DeepLabCut/napari-deeplabcut.git` and let me know if that solves your problem?

**Comment by jeylau** [comment]
I tested it once again: this bug is indeed fixed.
