### ISSUE TITLE
Incorrect comparison of images and the final markup file in h5 format

### ISSUE THREAD

**Issue by Tanya16181618** [DeepLabCut/napari-deeplabcut#63]
### Discussed in https://github.com/DeepLabCut/napari-deeplabcut/discussions/61

<div type='discussions-op-text'>

<sup>Originally posted by **Tanya16181618** February  9, 2023</sup>
Hi all!
I am using dlc version 2.3.0.
I came across the fact that in napari I have an incorrect match between the name of the photo and the markup itself in the h5 and csv file. Because of this, in my opinion, the neural network does not learn from me at all and I get bad results.
Attached is an example of such markup from the labled_data folder. For example, for photo 10.png there corresponds line 13 and photo 18.png. I calculated it so the results began to deteriorate, I began to check the markup. Moreover, in the graphical editor, the points are marked correctly, but not in the file. Tell me what can be done about it?
[3_Problem.zip](https://github.com/DeepLabCut/napari-deeplabcut/files/10698557/3_Problem.zip)
</div>

**Comment by jeylau** [comment]
Hello @Tanya16181618, this problem was fixed with https://github.com/DeepLabCut/napari-deeplabcut/commit/23bbb6fe80c01c9a66a168f6db8e37a85865ae0b. This was due to the way napari sorted images when their names were not zero-padded; i.e., photo 1.png should have been named 01.png, 2.png 02.png, etc. This would work now though with `napari-deeplabcut==0.1.2`.
